### ISSUE TITLE
ValueError: Component ID st7565_st7565 was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.

### ISSUE THREAD

**Issue by Digital-Ark** [monorkin/esphome_st7565#4]
Please see:

[https://github.com/landonr/lilygo-tdisplays3-esphome/pull/46](url)

In the last release of ESPHome, some small changes were done to the display component, to make subcomponents leaner. With those changes, compilation breaks if a display is trying to register as a component itself (this is now done automatically when registering the display).

**Comment by tikalin2000** [comment]
hello
there are somesolution available?

**Comment by monorkin** [comment]
Sorry, I missed this issue. I'll take a look at.

**Comment by monorkin** [comment]
Just [ported over the fix](https://github.com/monorkin/esphome_st7565/pull/5) that @Digital-Ark linked to, and verified that it works on my device with the latest Docker container.

@Digital-Ark or @tikalin2000 can one of you verify that [the fix](https://github.com/monorkin/esphome_st7565/pull/5) works for you?

**Comment by Digital-Ark** [comment]
![image](https://github.com/monorkin/esphome_st7565/assets/86251870/3a166fba-f72f-4c9c-a790-153e67db0af7)

Works for me!  Thanks for the fix!  Much appreciated.

**Comment by monorkin** [comment]
Thank you for the feedback and quick response @Digital-Ark !
I just merged the PR and broke release 1.1.0, to use it in your project you can specify `@1.1.0` instead of a branch.
